//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMail.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\t-mailip\\files\\")]
        public string InboxFolder {
            get {
                return ((string)(this["InboxFolder"]));
            }
            set {
                this["InboxFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\t-mailip\\BOXES\\V8001000.00\\")]
        public string OutboxFolder {
            get {
                return ((string)(this["OutboxFolder"]));
            }
            set {
                this["OutboxFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m:\\POST\\Inbox\\")]
        public string DelovodFolder {
            get {
                return ((string)(this["DelovodFolder"]));
            }
            set {
                this["DelovodFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\!!LUGANSK\\Входящие\\")]
        public string InboxArchiveFolder {
            get {
                return ((string)(this["InboxArchiveFolder"]));
            }
            set {
                this["InboxArchiveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\!!LUGANSK\\Исходящие\\")]
        public string OutboxArchiveFolder {
            get {
                return ((string)(this["OutboxArchiveFolder"]));
            }
            set {
                this["OutboxArchiveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\t-mailip\\BOXES\\V8001000.00\\Notkill\\")]
        public string OutboxNotkillFolder {
            get {
                return ((string)(this["OutboxNotkillFolder"]));
            }
            set {
                this["OutboxNotkillFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\computers.json")]
        public string ComputersInfoJSON {
            get {
                return ((string)(this["ComputersInfoJSON"]));
            }
            set {
                this["ComputersInfoJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d:\\Почта\\!ОТПРАВКА НА ЛУГАНСК\\")]
        public string OutboxSendingFolder {
            get {
                return ((string)(this["OutboxSendingFolder"]));
            }
            set {
                this["OutboxSendingFolder"] = value;
            }
        }
    }
}
